package nl.obren.sokrates.sourcecode.scoping;

import java.util.List;

/**
 * The standard conventions for ignored files (see the linguist sources listed in {@link ScopingConventions}).
 * Moved out of ScopingConventions, which keeps the other categories and applies them all.
 */
class IgnoreConventions {
    private IgnoreConventions() {
    }

    static void addTo(List<Convention> ignoredFilesConventions) {
        // Contents of well-known VCS / IDE / build-tool hidden directories. Deliberately a fixed
        // list rather than "any dotted folder", so real source under an incidentally-dotted folder
        // (e.g. src/.config/Foo.java) is not silently ignored.
        ignoredFilesConventions.add(new Convention("(.*/)?[.](git|svn|hg|bzr)/.*", "", "Hidden VCS/tool directories"));
        // Environment files typically hold local secrets/credentials, so they are dropped entirely.
        // Catches .env and its variants (.env.local, .env.production, …). Other tool dotfiles are
        // scoped as build-and-deployment instead (see addBuildAndDeploymentConventions).
        ignoredFilesConventions.add(new Convention("(.*/)?[.]env([.].*)?", "", "Environment files (secrets)"));
        ignoredFilesConventions.add(new Convention(".*[.]resx", "", "The resx resource files"));

        ignoredFilesConventions.add(new Convention(".*/node_modules/.*", "", "Node dependencies"));
        ignoredFilesConventions.add(new Convention(".*/git[-]history[.]txt", "", "Git history"));
        ignoredFilesConventions.add(new Convention(".*/git[-]commit[-]trailers[.]txt", "", "Git history trailers"));
        ignoredFilesConventions.add(new Convention(".*/git[-]merges[.]txt", "", "Git merges"));
        ignoredFilesConventions.add(new Convention(".*/bower_components/.*", "", "Bower components"));

        ignoredFilesConventions.add(new Convention(".*/[.]yarn/releases/.*", "", "Yarn releases"));
        ignoredFilesConventions.add(new Convention(".*/[.]yarn/plugins/.*", "", "Yarn plugins"));

        ignoredFilesConventions.add(new Convention(".*/target/.*", "", "Compiled files"));

        ignoredFilesConventions.add(new Convention(".*/bin/.*", "", "Binaries for distribution"));
        ignoredFilesConventions.add(new Convention(".*/cache/.*", "", "Caches"));
        ignoredFilesConventions.add(new Convention(".*/Godeps/.*", "", "Golang dependencies"));
        ignoredFilesConventions.add(new Convention(".*/[Vv]endors?/.*", "", "Dependencies"));
        ignoredFilesConventions.add(new Convention(".*/extern(al)?/.*", "", "Dependencies"));
        ignoredFilesConventions.add(new Convention(".*/(3rd|[Tt]hird)[-_]?[Pp]arty/.*", "", "Dependencies"));
        ignoredFilesConventions.add(new Convention(".*/deps/.*", "", "Dependencies"));
        ignoredFilesConventions.add(new Convention(".*/dist/.*", "", "Distributions"));
        ignoredFilesConventions.add(new Convention(".*/debian/.*", "", "Distributions"));
        ignoredFilesConventions.add(new Convention(".*[.]m4", "", "stuff autogenerated by autoconf - still C deps"));

        ignoredFilesConventions.add(new Convention("(?i).*/jquery.*[.]js", "", "jQuery files"));
        ignoredFilesConventions.add(new Convention("(?i).*/require.*[.]js", "", "RequireJS files"));
        ignoredFilesConventions.add(new Convention("(?i).*/libiconv/.*[.]js", "", "libincov files"));
        ignoredFilesConventions.add(new Convention(".*/docs/.*", "", "Documentation"));
        ignoredFilesConventions.add(new Convention(".*/bootstrap[.](js|css|less|scss|styl)", "", "Bootstrap"));
        ignoredFilesConventions.add(new Convention(".*[.]bootstrap[.](js|css|less|scss|styl)", "", "Bootstrap"));
        ignoredFilesConventions.add(new Convention(".*/bootstrap[-][a-z]+/.*", "", "Bootstrap"));
        ignoredFilesConventions.add(new Convention(".*/foundation[.](css|less|scss|styl)", "", "Foundation css"));
        ignoredFilesConventions.add(new Convention(".*/normalize[.](css|less|scss|styl)", "", "Normalize css"));
        ignoredFilesConventions.add(new Convention(".*/skeleton[.](css|less|scss|styl)", "", "Skeleton css"));
        ignoredFilesConventions.add(new Convention(".*/[Bb]ourbon[.](css|less|scss|styl)", "", "Bourbon css"));
        ignoredFilesConventions.add(new Convention(".*/animate[.](css|less|scss|styl)", "", "Animate css"));
        ignoredFilesConventions.add(new Convention(".*/materialize[.](js|css|less|scss|styl)", "", "Materialize css"));
        ignoredFilesConventions.add(new Convention(".*/select2[.](js|css|scss)", "", "Select2 css"));
        ignoredFilesConventions.add(new Convention(".*/bulma[.](css|sass|scss)", "", "Bulma css"));
        ignoredFilesConventions.add(new Convention(".*[.]min[.]js", "", "Minimized JS library"));
        ignoredFilesConventions.add(new Convention(".*[.]css[.]js", "", "Minimized CSS library"));
        ignoredFilesConventions.add(new Convention(".*tiny_mce_src[.]js", "", "Tiny MCE JS library"));
        ignoredFilesConventions.add(new Convention(".*/js/yui/.*", "", "YUI JS library"));
        ignoredFilesConventions.add(new Convention(".*/js/flotr/.*", "", "Flotr JS library"));
        ignoredFilesConventions.add(new Convention(".*[.]import[.](css|less|scss|styl)", "", "Stylesheets imported from packages"));
        ignoredFilesConventions.add(new Convention(".*font-?awesome\\.(css|less|scss|styl)", "", "Font Awesome"));
        ignoredFilesConventions.add(new Convention(".*font-?awesome/.*\\.(css|less|scss|styl)", "", "Font Awesome"));
        ignoredFilesConventions.add(new Convention(".*/fuelux[.]js", "", "Fuel UX"));
        ignoredFilesConventions.add(new Convention(".*/bootbox[.]js", "", "Bootbox"));
        ignoredFilesConventions.add(new Convention(".*/pdf[-]worker[.]js", "", "pdf-worker"));
        ignoredFilesConventions.add(new Convention(".*/slick\\.\\w+.js", "", "Slick"));
        ignoredFilesConventions.add(new Convention(".*/prototype(.*)\\.js", "", "Prototype"));
        ignoredFilesConventions.add(new Convention(".*/effects\\.js", "", "Prototype"));
        ignoredFilesConventions.add(new Convention(".*/controls\\.js", "", "Prototype"));
        ignoredFilesConventions.add(new Convention(".*/dragdrop\\.js", "", "Prototype"));
        ignoredFilesConventions.add(new Convention(".*\\.d\\.ts", "", "Typescript definition files"));
        ignoredFilesConventions.add(new Convention(".*/mootools([^.]*)\\d+\\.\\d+.\\d+([^.]*)\\.js", "", "MooTools"));
        ignoredFilesConventions.add(new Convention(".*/dojo\\.js", "", "Dojo"));
        ignoredFilesConventions.add(new Convention(".*/MochiKit\\.js", "", "MochiKit"));
        ignoredFilesConventions.add(new Convention(".*/yahoo-([^.]*)\\.js", "", "YUI"));
        ignoredFilesConventions.add(new Convention(".*/yui([^.]*)\\.js", "", "YUI"));
        ignoredFilesConventions.add(new Convention(".*/underscore\\.js", "", "Underscore.js"));
        ignoredFilesConventions.add(new Convention(".*/typeahead\\.js", "", "Typeahead.js"));

        ignoredFilesConventions.add(new Convention(".*/Leaflet\\.Coordinates-\\d+\\.\\d+\\.\\d+\\.src\\.js", "", "Leaflet plugins"));
        ignoredFilesConventions.add(new Convention(".*/leaflet[.]draw[-]src[.]js", "", "Leaflet plugins"));
        ignoredFilesConventions.add(new Convention(".*/leaflet[.]draw[.]css", "", "Leaflet plugins"));
        ignoredFilesConventions.add(new Convention(".*/Control[.]FullScreen[.]css", "", "Leaflet plugins"));
        ignoredFilesConventions.add(new Convention(".*/Control[.]FullScreen[.]js", "", "Leaflet plugins"));
        ignoredFilesConventions.add(new Convention(".*/leaflet[.]spin[.]js", "", "Leaflet plugins"));
        ignoredFilesConventions.add(new Convention(".*/wicket[-]leaflet[.]js", "", "Leaflet plugins"));

        ignoredFilesConventions.addAll(ScopingConventions.SOKRATES_OUTPUT_CONVENTIONS);

        ignoredFilesConventions.add(new Convention(".*/testdata/.*", "", "Test data"));
        ignoredFilesConventions.add(new Convention(".*/Godeps/_workspace/.*", "", "Go dependencies"));

        ignoredFilesConventions.add(new Convention(".*/_esy/.*", "", "esy.sh dependencies"));

        ignoredFilesConventions.add(new Convention(".*/ckeditor[.]js", "", "WYS editors"));
        ignoredFilesConventions.add(new Convention(".*/tiny_mce([^.]*)\\.j", "", "WYS editors"));
        ignoredFilesConventions.add(new Convention(".*/tiny_mce/(langs|plugins|themes|utils)/.*", "", "WYS editors"));

        ignoredFilesConventions.add(new Convention(".*/ace-builds/.*", "", "Ace Editor"));
        ignoredFilesConventions.add(new Convention(".*/MathJax/.*", "", "MathJax"));
        ignoredFilesConventions.add(new Convention(".*/fontello(.*?)\\.css", "", "Fontello CSS files"));
        ignoredFilesConventions.add(new Convention(".*/Chart\\.js", "", "Chart.js"));

        ignoredFilesConventions.add(new Convention(".*/[Cc]ode[Mm]irror/(\\d+\\.\\d+/)?(lib|mode|theme|addon|keymap|demo)/.*", "", "CodeMirror"));

        ignoredFilesConventions.add(new Convention(".*/shBrush([^.]*)\\.js", "", "SyntaxHighlighter - http://alexgorbatchev.com/"));
        ignoredFilesConventions.add(new Convention(".*/shCore\\.js", "", "SyntaxHighlighter - http://alexgorbatchev.com/"));
        ignoredFilesConventions.add(new Convention(".*/shLegacy\\.js", "", "SyntaxHighlighter - http://alexgorbatchev.com/"));

        ignoredFilesConventions.add(new Convention(".*/angular([^.]*)\\.js", "", "AngularJS"));
        ignoredFilesConventions.add(new Convention(".*/react(-[^.]*)?\\.js", "", "React"));
        ignoredFilesConventions.add(new Convention(".*/d3(\\.v\\d+)?([^.]*)\\.js", "", "D3"));
        ignoredFilesConventions.add(new Convention(".*/flow-typed/.*\\.js", "", "flow-typed"));

        ignoredFilesConventions.add(new Convention(".*/modernizr\\-\\d\\.\\d+(\\.\\d+)?\\.js", "", "Modernizr"));
        ignoredFilesConventions.add(new Convention(".*/modernizr\\.custom\\.\\d+\\.js", "", "Modernizr"));

        ignoredFilesConventions.add(new Convention(".*/knockout-(\\d+\\.){3}(debug\\.)?js", "", "Knockout"));

        ignoredFilesConventions.add(new Convention(".*/docs?/_?(build|themes?|templates?|static)/.*", "", "Sphinx"));

        ignoredFilesConventions.add(new Convention(".*/admin_media/.*", "", "django"));

        ignoredFilesConventions.add(new Convention(".*/fabfile\\.py", "", "Fabric"));

        ignoredFilesConventions.add(new Convention(".*[.]osx", "", ".osx"));

        ignoredFilesConventions.add(new Convention(".*/Carthage/.*", "", "Carthage"));
        ignoredFilesConventions.add(new Convention(".*/Sparkle/.*", "", "Sparkle"));
        ignoredFilesConventions.add(new Convention(".*/Fabric[.]framework/.*", "", "Fabric.framework"));
        ignoredFilesConventions.add(new Convention(".*/BuddyBuildSDK[.]framework/.*", "", "BuddyBuildSDK.framework"));
        ignoredFilesConventions.add(new Convention(".*/Realm[.]framework/.*", "", "Realm.framework"));
        ignoredFilesConventions.add(new Convention(".*/RealmSwift[.]framework/.*", "", "RealmSwift.framework"));

        ignoredFilesConventions.add(new Convention(".*/gradlew", "", "Gradle"));
        ignoredFilesConventions.add(new Convention(".*/gradle/wrapper/.*", "", "Gradle"));

        ignoredFilesConventions.add(new Convention(".*/mvnw", "", "Maven"));
        ignoredFilesConventions.add(new Convention(".*/mvnw\\.cmd", "", "Maven"));

        ignoredFilesConventions.add(new Convention(".*[-]vsdoc\\.js", "", "Visual Studio IntelliSense"));

        ignoredFilesConventions.add(new Convention(".*/jquery([^.]*)\\.validate(\\.unobtrusive)?\\.js", "", "jQuery validation plugin (MS bundles this with asp.net mvc)"));
        ignoredFilesConventions.add(new Convention(".*/jquery([^.]*)\\.unobtrusive\\-ajax\\.js", "", "jQuery validation plugin (MS bundles this with asp.net mvc)"));
        ignoredFilesConventions.add(new Convention(".*jquery[.].*[.]js", "", "jQuery library"));

        ignoredFilesConventions.add(new Convention(".*/[Mm]icrosoft([Mm]vc)?([Aa]jax|[Vv]alidation)(\\.debug)?\\.js", "", "Microsoft Ajax"));

        ignoredFilesConventions.add(new Convention(".*/[Pp]ackages\\/.+\\.\\d+\\/.*", "", "NuGet"));

        ignoredFilesConventions.add(new Convention(".*/extjs/.*?\\.(js|xml|txt|html|properties)", "", "ExtJS"));
        ignoredFilesConventions.add(new Convention(".*/extjs/[.]sencha/.*", "", "ExtJS"));
        ignoredFilesConventions.add(new Convention(".*/extjs/docs/", "", "ExtJS"));
        ignoredFilesConventions.add(new Convention(".*/extjs/builds/", "", "ExtJS"));
        ignoredFilesConventions.add(new Convention(".*/extjs/cmd/", "", "ExtJS"));
        ignoredFilesConventions.add(new Convention(".*/extjs/examples/", "", "ExtJS"));
        ignoredFilesConventions.add(new Convention(".*/extjs/locale/", "", "ExtJS"));
        ignoredFilesConventions.add(new Convention(".*/extjs/packages/", "", "ExtJS"));
        ignoredFilesConventions.add(new Convention(".*/extjs/plugins/", "", "ExtJS"));
        ignoredFilesConventions.add(new Convention(".*/extjs/resources/", "", "ExtJS"));
        ignoredFilesConventions.add(new Convention(".*/extjs/src/", "", "ExtJS"));
        ignoredFilesConventions.add(new Convention(".*/extjs/welcome/", "", "ExtJS"));

        ignoredFilesConventions.add(new Convention(".*/html5shiv\\.js", "", "Html5shiv"));

        ignoredFilesConventions.add(new Convention(".*/cordova([^.]*)\\.js", "", "PhoneGap/Cordova"));
        ignoredFilesConventions.add(new Convention(".*/cordova\\-\\d\\.\\d(\\.\\d)?\\.js", "", "PhoneGap/Cordova"));

        ignoredFilesConventions.add(new Convention(".*/foundation(\\..*)?\\.js", "", "Foundation js"));

        ignoredFilesConventions.add(new Convention(".*/Vagrantfile", "", "Vagrant"));

        ignoredFilesConventions.add(new Convention(".*/.[Dd][Ss]_[Ss]tore", "", ".DS_Stores"));
        ignoredFilesConventions.add(new Convention(".*/.[Dd][Ss]_[Ss]tore/.*", "", ".DS_Stores"));

        ignoredFilesConventions.add(new Convention(".*/vignettes/.*", "", "R packages"));
        ignoredFilesConventions.add(new Convention(".*/inst/extdata/.*", "", "R packages"));

        ignoredFilesConventions.add(new Convention(".*/octicons[.]css", "", "Octicons"));
        ignoredFilesConventions.add(new Convention(".*/sprockets[-]octicons[.]scss", "", "Octicons"));

        ignoredFilesConventions.add(new Convention(".*/activator", "", "Typesafe Activator"));
        ignoredFilesConventions.add(new Convention(".*/activator\\.bat", "", "Typesafe Activator"));

        ignoredFilesConventions.add(new Convention(".*/proguard[.]pro", "", "ProGuard"));
        ignoredFilesConventions.add(new Convention(".*/proguard[-]rules[.]pro", "", "ProGuard"));

        ignoredFilesConventions.add(new Convention(".*/puphpet/.*", "", "PuPHPet"));

        ignoredFilesConventions.add(new Convention(".*/[Gg]roovydoc/.*", "", "Generated documentation"));
        ignoredFilesConventions.add(new Convention(".*/[Jj]avadoc/.*", "", "Generated documentation"));
        ignoredFilesConventions.add(new Convention(".*/inst/doc/.*", "", "Generated documentation"));

        ignoredFilesConventions.add(new Convention(".*/Thumbs[.]db", "", "Thumbs.db"));
        ignoredFilesConventions.add(new Convention(".*/__MACOSX/.*", "", "__MACOSX folder"));

        ignoredFilesConventions.add(new Convention(".*/www/bundles[-]www/.*", "", "Web bundles"));
    }
}
