package nl.obren.sokrates.reports.core;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

class ReportNavigationTest {

    private ReportNavigation navigation() {
        ReportNavigation navigation = new ReportNavigation("acme/<b>repo</b>", "index.html#overview");
        navigation.addGroup("Report")
                .addTabItem("overview", "Overview", "index.html#overview", "overview")
                .addTabItem("custom_tab_0", "My <tab>", "index.html#custom_tab_0", "custom");
        navigation.addGroup("Analyses")
                .addItem("Duplication.html", "Duplication", "Duplication.html", "duplication")
                .addItem("FileSize.html", "File Size", "FileSize.html", "no-such-icon");
        return navigation;
    }

    @Test
    void marksOnlyTheActivePageAndRoutesIndexTabs() {
        String html = navigation().render("Duplication.html");

        assertTrue(html.contains("<a class='sk-nav-item active' href='Duplication.html' data-sk-nav='Duplication.html' aria-current='page'>"), html);
        assertEquals(1, html.split("aria-current").length - 1);
        assertTrue(html.contains("href='index.html#overview' data-sk-nav='overview' data-sk-tab='overview' data-sk-subtitle=''>"));
        assertFalse(html.contains("data-sk-nav='Duplication.html' data-sk-tab"), "a report page is not a tab");
    }

    @Test
    void escapesTheRepositoryNameAndConfiguredLabels() {
        String html = navigation().render("overview");

        assertFalse(html.contains("repo"), "the repository name is in the page header, not the sidebar");
        assertEquals("<a class='sk-page-context' href='index.html#overview'>acme/&lt;b&gt;repo&lt;/b&gt;</a>", navigation().contextLineHtml());
        assertTrue(html.contains("<span class='sk-nav-label'>My &lt;tab&gt;</span>"));
        assertFalse(html.contains("My <tab>"));
    }

    @Test
    void thePageTitleIsTheLabelOfThePagesSidebarItem() {
        RichTextReport report = new RichTextReport("Metrics", "Metrics.html");
        assertNull(ReportNavigation.pageTitle(report), "no sidebar, no page title");

        ReportNavigation navigation = navigation();
        report.setNavigation(navigation, "FileSize.html");
        assertEquals("File Size", ReportNavigation.pageTitle(report));
        report.setNavigation(navigation, "custom_tab_0");
        assertEquals("My <tab>", ReportNavigation.pageTitle(report));
        report.setNavigation(navigation, "Trend.html");
        assertNull(ReportNavigation.pageTitle(report), "a page that is not in the sidebar keeps its own title");
        report.setNavigation(navigation, "FileSize.html");
        report.setEmbedded(true);
        assertNull(ReportNavigation.pageTitle(report), "embedded pages have no shell");
    }

    @Test
    void indexTabsCarryTheirSubtitleForTheHeader() {
        ReportNavigation navigation = new ReportNavigation("repo", "index.html#overview");
        navigation.addGroup("At a Glance").addTabItem("overview", "Overview", "index.html#overview", "overview", "Size & <age>");
        navigation.addGroup("Analyses").addItem("Duplication.html", "Duplication", "Duplication.html", "duplication");

        assertEquals("Size & <age>", navigation.subtitleOf("overview"));
        assertNull(navigation.subtitleOf("Duplication.html"), "a report page uses its own description");
        assertTrue(navigation.render("overview").contains("data-sk-subtitle='Size &amp; &lt;age&gt;'"));
    }

    @Test
    void theSidebarFooterSaysWhatGeneratedTheReportAndWhen() {
        ReportNavigation navigation = navigation();
        navigation.setGeneratedOn("2026-10-03", null);
        String html = navigation.render("");
        assertTrue(html.contains("generated by <a target='_blank' href='https://sokrates.dev/'>sokrates.dev</a><br>on 2026-10-03"), html);
        assertTrue(html.contains("onclick=\"return downloadDataFile('config.json')\">config</a>"));
        assertFalse(html.contains("reference date"));

        navigation.setGeneratedOn("2026-10-03", "2026-01-01");
        assertTrue(navigation.render("").contains("<br>reference date: 2026-01-01"));
    }

    @Test
    void rendersKnownIconsAndNothingForUnknownOnes() {
        String html = navigation().render("");

        assertTrue(html.contains("<span class='sk-nav-icon'><svg width='16' height='16'"));
        assertTrue(html.contains("<span class='sk-nav-icon'></span><span class='sk-nav-label'>File Size</span>"));
        assertTrue(html.contains("class='sk-nav-search-input'"));
        assertTrue(html.contains("oninput='sokratesFilterNav(this.value)'"));
        assertFalse(html.contains("sokratesOpenPalette"));
        assertTrue(html.contains("class='sk-nav-toggle'"));
    }

    @Test
    void theOverviewCanShowTheConfiguredNameAsItsTitle() {
        ReportNavigation navigation = navigation();
        assertEquals("Overview", navigation.titleOf("overview"));

        navigation.setPageTitle("overview", "  ");
        assertEquals("Overview", navigation.titleOf("overview"), "a blank name keeps the label");

        navigation.setPageTitle("overview", "acme/<b>repo</b>");
        assertEquals("acme/<b>repo</b>", navigation.titleOf("overview"));
        assertEquals("Overview", navigation.labelOf("overview"), "the sidebar label stays");
        String html = navigation.render("overview");
        assertTrue(html.contains("data-sk-title='acme/&lt;b&gt;repo&lt;/b&gt;'"), html);
        assertTrue(html.contains("<span class='sk-nav-label'>Overview</span>"));
        // The context line would repeat the title, so it starts hidden; other pages show it.
        assertTrue(navigation.contextLineHtml("acme/<b>repo</b>").contains(" hidden>"));
        assertFalse(navigation.contextLineHtml("Duplication").contains("hidden"));
    }

    @Test
    void theOverviewCanShowTheConfiguredLogoAsItsIcon() {
        ReportNavigation navigation = navigation();
        String icon = navigation.iconOf("overview", 68);
        assertTrue(icon.startsWith("<svg width='68'"), icon);

        navigation.setPageIcon("overview", " ");
        assertEquals(icon, navigation.iconOf("overview", 68), "a blank logo keeps the icon");

        navigation.setPageIcon("overview", "https://example.com/logo.png?a=1&b='2'");
        String logo = navigation.iconOf("overview", 68);
        assertTrue(logo.startsWith("<img class='sk-page-logo' src='https://example.com/logo.png?a=1&amp;b=&#39;2&#39;'"), logo);
        assertTrue(logo.contains("<span hidden>" + icon + "</span>"), "the icon stays as the fallback");
        assertTrue(navigation.render("overview").contains("data-sk-icon-src='https://example.com/logo.png?a=1&amp;b=&#39;2&#39;'"));
        assertFalse(navigation.render("overview").contains("<img"), "the sidebar keeps its icon");
    }

    @Test
    void subTabItemsOpenATabWithItsFramePointedAtAnotherUrl() {
        ReportNavigation navigation = new ReportNavigation("Landscape", "index.html#overview");
        navigation.addGroup("Landscape")
                .addTabItem("repositories", "Repositories", "index.html#repositories", "repositories")
                .addSubTabItem("repositories-list", "churnTrend", "Churn", "repositories", "repositories.html?tab=churnTrend", "Churn per repository.");
        navigation.setPageTitle("repositories-list/churnTrend", "Repositories: Churn");

        String html = navigation.render("repositories");

        assertTrue(html.contains("class='sk-nav-item sk-nav-sub' href='index.html#repositories-list/churnTrend' data-sk-nav='repositories-list/churnTrend'"), html);
        assertTrue(html.contains("data-sk-frame-src='repositories.html?tab=churnTrend'"));
        assertTrue(html.contains("data-sk-tab='repositories-list'"));
        assertEquals("Repositories: Churn", navigation.titleOf("repositories-list/churnTrend"));
        assertEquals(navigation.iconOf("repositories", 68), navigation.iconOf("repositories-list/churnTrend", 68), "the header shows the parent's icon");
    }

    @Test
    void groupLabelsOpenAndCloseTheirItems() {
        ReportNavigation navigation = new ReportNavigation("Repo", "index.html#overview");
        navigation.addGroup("R&D <tools>").addTabItem("overview", "Overview", "index.html#overview", "overview");
        String html = navigation.render("overview");

        assertTrue(html.contains("<div class='sk-nav-group' data-sk-group='R&amp;D &lt;tools&gt;'>"), html);
        assertTrue(html.contains("<button type='button' class='sk-nav-group-label' aria-expanded='true' onclick='sokratesToggleNavGroup(this)'>"
                + "<span>R&amp;D &lt;tools&gt;</span>"), "open by default, the label escaped");
        assertTrue(html.contains("<div class='sk-nav-group-items'>"));
        assertTrue(html.indexOf("sokratesRestoreNavGroups()") > html.indexOf("</nav>"), "the closed groups are restored right after the sidebar");
    }
}
